config/routes.rb
Rails.application.routes.draw do
  resources :deals
  devise_for :users

  resources :deals

  get "deals/:id/buy", to: "deals#buy"

  root to: "deals#index"

end

app/models/deal.rb
class Deal < ActiveRecord::Base

  before_create :set_defaults

  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/assets/images/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  validates :publish_date,presence:true, uniqueness: true
  validates :title,presence:true, :uniqueness => {:case_sensitive => false}

  validates_presence_of :price, :discounted_price

  def set_defaults
    self.is_live = false
    true
  end

end

app/models/service.rb
class Service
  class << self

    def flash_sale
      Deal.all.update_all(is_live:false)
      todays_deal = Deal.where(publish_date: Time.current.to_date).first
      todays_deal.update_columns(is_live: true) if todays_deal.present?
    end

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_deals

end

app/models/user_deal.rb
class UserDeal < ActiveRecord::Base

  belongs_to :user
  belongs_to :deal

  after_create :decrement_deal

  def decrement_deal
    self.deal.update_columns(quantity: self.deal.quantity - 1)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_deal, only: [:show, :edit, :update, :destroy, :buy]

  # GET /deals
  # GET /deals.json
  def index
    if current_user.is_admin?
      @deals = Deal.all
    else
      @deal_of_the_day = Deal.where(is_live:true).limit(1)
      @bought_deals = current_user.user_deals
      bought_deal_ids = @bought_deals.pluck(:deal_id)
      if bought_deal_ids.include? @deal_of_the_day.first.try(:id)
        @already_bought = true
      else
        @already_bought = false
      end
    end
  end

  def buy
    discount = current_user.user_deals.count < 5 ? current_user.user_deals.count : 5
    if current_user.user_deals.create!(deal_id: @deal.id, discount: discount)
      respond_to do |format|
        format.html { redirect_to deals_url, notice: 'Deal was Bought.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to deals_url, notice: 'Some Error Occured' }
        format.json { head :no_content }
      end
    end
  end

  # GET /deals/1
  # GET /deals/1.json
  def show
  end

  # GET /deals/new
  def new
    @deal = Deal.new
  end

  # GET /deals/1/edit
  def edit
  end

  # POST /deals
  # POST /deals.json
  def create
    @deal = Deal.new(deal_params)

    respond_to do |format|
      if @deal.save
        format.html { redirect_to @deal, notice: 'Deal was successfully created.' }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1
  # PATCH/PUT /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to @deal, notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1
  # DELETE /deals/1.json
  def destroy
    @deal.destroy
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deal
      @deal = Deal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deal_params
      params.require(:deal).permit(:title, :is_live, :discription, :price, :discounted_price, :quantity, :publish_date, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<%= form_for(@deal) do |f| %>
  <% if @deal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

      <ul>
      <% @deal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :discription %><br>
    <%= f.text_area :discription %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :discounted_price %><br>
    <%= f.text_field :discounted_price %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :publish_date %><br>
    <%= f.date_select :publish_date %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, as: :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing Deal</h1>

<%= render 'form' %>

<%= link_to 'Show', @deal %> |
<%= link_to 'Back', deals_path %>

app/views/deals/index.html.erb
<%if current_user.is_admin?%>
  <h1>Listing Deals</h1>

  <table class='table table-striped table-bordered table-advance table-hover'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Is live</th>
        <th>Discription</th>
        <th>Price</th>
        <th>Discounted price</th>
        <th>Quantity</th>
        <th>Publish date</th>
        <th>Attachment</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @deals.each do |deal| %>
        <tr>
          <td><%= deal.title %></td>
          <td><%= deal.is_live %></td>
          <td><%= deal.discription %></td>
          <td><%= deal.price %></td>
          <td><%= deal.discounted_price %></td>
          <td><%= deal.quantity %></td>
          <td><%= deal.publish_date.to_datetime.strftime("%d-%m-%Y") %></td>
          <td><%= image_tag deal.image.url(:thumb) %></td>
          <td><%= link_to 'Show', deal %></td>
          <td><%= link_to 'Edit', edit_deal_path(deal) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Deal', new_deal_path %>
<%else%>
  <h1>Deal of The Day</h1>

  <table class='table table-striped table-bordered table-advance table-hover'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Is live</th>
        <th>Discription</th>
        <th>Price</th>
        <th>Discounted price</th>
        <th>Quantity</th>
        <th>Publish date</th>
        <th>Attachment</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @deal_of_the_day.each do |deal| %>
        <tr>
          <td><%= deal.title %></td>
          <td><%= deal.is_live %></td>
          <td><%= deal.discription %></td>
          <td><%= deal.price %></td>
          <td><%= deal.discounted_price %></td>
          <td><%= deal.quantity %></td>
          <td><%= deal.publish_date %></td>
          <td><%= image_tag deal.image.url(:thumb) %></td>
          <td>
            <% if deal.quantity == 0 %>
              Out of Sale
            <%else%>
              <%if @already_bought%>
                Already Bought
              <%else%>
                <a data-confirm="Are you sure you want to buy?" href="/deals/<%=deal.id%>/buy">Buy</a>
              <%end%>
            <%end%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<hr>

  <h1>Bought Deals</h1>

  <table class='table table-striped table-bordered table-advance table-hover'>
    <thead>
      <tr>
        <th>Title</th>
        <th>Discount(%)</th>
        <th>Date</th>
        <th>Image</th>
      </tr>
    </thead>

    <tbody>
      <% @bought_deals.each do |user_deal| %>
        <tr>
          <td><%= user_deal.deal.title %></td>
          <td><%= user_deal.discount %></td>
          <td><%= user_deal.created_at.strftime("%d-%m-%Y") %></td>
          <td><%= image_tag user_deal.deal.image.url(:thumb) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<%end%>

app/views/deals/new.html.erb
<h1>New Deal</h1>

<%= render 'form' %>

<%= link_to 'Back', deals_path %>

app/views/deals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @deal.title %>
</p>

<p>
  <strong>Is live:</strong>
  <%= @deal.is_live %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @deal.discription %>
</p>

<p>
  <strong>Price:</strong>
  <%= @deal.price %>
</p>

<p>
  <strong>Discounted price:</strong>
  <%= @deal.discounted_price %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @deal.quantity %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @deal.publish_date %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @deal.image.url(:thumb) %>
</p>

<%= link_to 'Edit', edit_deal_path(@deal) %> |
<%= link_to 'Back', deals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flash Sale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"%>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js","https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"%>
  <%= csrf_meta_tags %>
</head>
<body style="background-color: lightblue;">

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= deals_path %>">Flash Sales</a>
    </div>
    <ul class="nav navbar-nav">
      <% if user_signed_in? %>
        <li><a href="<%= deals_path %>">Deals</a></li>
      <% end %>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li><a href="<%= deals_path %>">Logged in as : <%= current_user.email%></a></li>
        <li><a data-method="delete" href="<%=destroy_user_session_path%>"><span class="glyphicon glyphicon-user"></span> Sign Out</a></li>
      <% else %>
        <li><a href="<%=new_user_registration_path%>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="<%=new_user_session_path%>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <% end %>
    </ul>
  </div>
</nav>

<div class="container rcorners1">
  <div class="col-md-12">
    <% if notice.present? %>
      <p class="alert alert-success"><%= notice %></p>
    <%elsif alert.present?%>
      <p class="alert alert-danger"><%= alert %></p>
    <% end%>
    <%= yield %>
  </div>
</div>

</body>
</html>